general.import = [ '~/.config/alacritty/rose-pine.toml' ]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 16.5

[font.normal]
family = 'SF Mono'
style = 'Regular'

[font.italic]
family = 'SF Mono'
style = 'Italic'

[font.bold]
family = 'SF Mono'
style = 'SemiBold'

[font.bold_italic]
family = 'SF Mono'
style = 'Italic'

[window]
opacity = 0.95
padding = { x = 0, y = 0 }
decorations = 'None'
startup_mode = 'Maximized'
